version: "3.8"
services:
  postgres:
    image: "docker.io/library/postgres:12.0"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./people.v2.csv:/opt/people.v2.csv"

  core:
    image: "core:latest"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres

